# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Testing gorleaser with homebrew"
  homepage "https://github.com/jsumners-nr/cli-tool-testing"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.1.0/hello_world_0.1.0_darwin_amd64.tar.gz"
      sha256 "6b43e628f86ee5386e42cd453e35da1f0c805c9b5f26381c5e7db106b40d96ef"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.1.0/hello_world_0.1.0_darwin_arm64.tar.gz"
      sha256 "f1ac007267dee900ffa80332c37a1fb86805104874b77df1645bd94c07132eff"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.1.0/hello_world_0.1.0_linux_amd64.tar.gz"
        sha256 "2f1c443882c4569ed9b229bd70a09fc6141b63088a24b39cb45b746551d2fa6b"

        def install
          bin.install "hello"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.1.0/hello_world_0.1.0_linux_arm64.tar.gz"
        sha256 "00cf58c2fd7a36cfd419cf73f48acd6c98e3287c61792e978d5759254ef69bd5"

        def install
          bin.install "hello"
        end
      end
    end
  end
end
