# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Testing gorleaser with homebrew"
  homepage "https://github.com/jsumners-nr/cli-tool-testing"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.4.0/hello_world_0.4.0_darwin_amd64.tar.gz"
      sha256 "75e83cb348b11daf797856025ceb9da0eda6d04c450f5a84a7da8eb59cbf57b5"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.4.0/hello_world_0.4.0_darwin_arm64.tar.gz"
      sha256 "1fbe122210d425861e10d6b18ca6b2dcf09a6a6f60e51f156c7c47a9c37e2384"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.4.0/hello_world_0.4.0_linux_amd64.tar.gz"
        sha256 "d91a55a44a706b599ba9e6640eadb4f608e8b9f967aa95596d44b728821f7dc9"

        def install
          bin.install "hello"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jsumners-nr/cli-tool-testing/releases/download/v0.4.0/hello_world_0.4.0_linux_arm64.tar.gz"
        sha256 "ebcddd9309c40125ee8e9a581742497e5b3edb2ce8e6d73702d9123c694963b6"

        def install
          bin.install "hello"
        end
      end
    end
  end
end
